import type { FilterFieldConfig } from '@/widgets/common/filter/filter-sidebar/model/types';

export const drawingFilterFields: FilterFieldConfig[] = [
  {
    key: 'drawingNumber',
    label: '図番',
    type: 'text',
    placeholder: '図番を入力',
  },
  {
    key: 'name',
    label: '図面名',
    type: 'text',
    placeholder: '図面名を入力',
  },
  {
    key: 'revision',
    label: 'Rev',
    type: 'multiselect',
    options: [
      { label: 'A', value: 'A' },
      { label: 'B', value: 'B' },
      { label: 'C', value: 'C' },
      { label: 'D', value: 'D' },
      { label: 'E', value: 'E' },
    ],
  },
  {
    key: 'status',
    label: 'ステータス',
    type: 'multiselect',
    options: [
      { label: '承認済', value: '承認済', color: '#22c55e' },
      { label: 'レビュー中', value: 'レビュー中', color: '#f59e0b' },
      { label: '作成中', value: '作成中', color: '#3b82f6' },
      { label: '却下', value: '却下', color: '#ef4444' },
      { label: '保留', value: '保留', color: '#6b7280' },
    ],
  },
  {
    key: 'category',
    label: 'カテゴリ',
    type: 'multiselect',
    options: [
      { label: '組立図', value: '組立図' },
      { label: '加工図', value: '加工図' },
      { label: '部品図', value: '部品図' },
      { label: 'レイアウト図', value: 'レイアウト図' },
      { label: '外観図', value: '外観図' },
      { label: '配線図', value: '配線図' },
      { label: '回路図', value: '回路図' },
      { label: '構造図', value: '構造図' },
    ],
  },
  {
    key: 'project',
    label: 'プロジェクト',
    type: 'multiselect',
    options: [
      { label: 'プロジェクトA', value: 'プロジェクトA' },
      { label: 'プロジェクトB', value: 'プロジェクトB' },
      { label: 'プロジェクトC', value: 'プロジェクトC' },
      { label: 'プロジェクトD', value: 'プロジェクトD' },
      { label: '新製品開発', value: '新製品開発' },
      { label: '改良案件', value: '改良案件' },
    ],
  },
  {
    key: 'department',
    label: '部署',
    type: 'multiselect',
    options: [
      { label: '設計1課', value: '設計1課' },
      { label: '設計2課', value: '設計2課' },
      { label: '製造技術課', value: '製造技術課' },
      { label: '品質管理課', value: '品質管理課' },
      { label: '開発課', value: '開発課' },
    ],
  },
  {
    key: 'createdBy',
    label: '作成者',
    type: 'user',
    userOptions: [
      { id: '山田太郎', name: '山田太郎' },
      { id: '佐藤花子', name: '佐藤花子' },
      { id: '田中一郎', name: '田中一郎' },
      { id: '鈴木次郎', name: '鈴木次郎' },
      { id: '高橋美咲', name: '高橋美咲' },
      { id: '伊藤健太', name: '伊藤健太' },
      { id: '渡辺真理', name: '渡辺真理' },
      { id: '小林誠', name: '小林誠' },
    ],
  },
  {
    key: 'createdAt',
    label: '作成日',
    type: 'date',
  },
  {
    key: 'updatedBy',
    label: '更新者',
    type: 'user',
    userOptions: [
      { id: '山田太郎', name: '山田太郎' },
      { id: '佐藤花子', name: '佐藤花子' },
      { id: '田中一郎', name: '田中一郎' },
      { id: '鈴木次郎', name: '鈴木次郎' },
      { id: '高橋美咲', name: '高橋美咲' },
      { id: '伊藤健太', name: '伊藤健太' },
      { id: '渡辺真理', name: '渡辺真理' },
      { id: '小林誠', name: '小林誠' },
    ],
  },
  {
    key: 'updatedAt',
    label: '更新日',
    type: 'date',
  },
  {
    key: 'approvedBy',
    label: '承認者',
    type: 'user',
    userOptions: [
      { id: '部長 中村', name: '部長 中村' },
      { id: '課長 木村', name: '課長 木村' },
      { id: '主任 加藤', name: '主任 加藤' },
      { id: '係長 吉田', name: '係長 吉田' },
    ],
  },
  {
    key: 'fileFormat',
    label: 'ファイル形式',
    type: 'multiselect',
    options: [
      { label: 'DWG', value: 'DWG' },
      { label: 'DXF', value: 'DXF' },
      { label: 'PDF', value: 'PDF' },
      { label: 'STEP', value: 'STEP' },
      { label: 'IGES', value: 'IGES' },
    ],
  },
  {
    key: 'scale',
    label: '縮尺',
    type: 'multiselect',
    options: [
      { label: '1:1', value: '1:1' },
      { label: '1:2', value: '1:2' },
      { label: '1:5', value: '1:5' },
      { label: '1:10', value: '1:10' },
      { label: '1:20', value: '1:20' },
      { label: '1:50', value: '1:50' },
      { label: '1:100', value: '1:100' },
    ],
  },
  {
    key: 'sheetSize',
    label: '用紙サイズ',
    type: 'multiselect',
    options: [
      { label: 'A0', value: 'A0' },
      { label: 'A1', value: 'A1' },
      { label: 'A2', value: 'A2' },
      { label: 'A3', value: 'A3' },
      { label: 'A4', value: 'A4' },
    ],
  },
  {
    key: 'material',
    label: '材質',
    type: 'multiselect',
    options: [
      { label: 'SS400', value: 'SS400' },
      { label: 'SUS304', value: 'SUS304' },
      { label: 'A5052', value: 'A5052' },
      { label: 'S45C', value: 'S45C' },
      { label: 'SUS316', value: 'SUS316' },
      { label: 'C1100', value: 'C1100' },
      { label: 'ABS樹脂', value: 'ABS樹脂' },
      { label: 'POM', value: 'POM' },
    ],
  },
  {
    key: 'tags',
    label: 'タグ',
    type: 'multiselect',
    options: [
      { label: '重要', value: '重要', color: '#ef4444' },
      { label: '緊急', value: '緊急', color: '#f97316' },
      { label: '新規', value: '新規', color: '#3b82f6' },
      { label: '改訂', value: '改訂', color: '#8b5cf6' },
      { label: '試作', value: '試作', color: '#06b6d4' },
      { label: '量産', value: '量産', color: '#22c55e' },
      { label: '外注', value: '外注', color: '#ec4899' },
      { label: '内製', value: '内製', color: '#14b8a6' },
    ],
  },
];
