export interface CustomerItem {
  id: number;
  customerCode: string;
  companyName: string;
  department: string;
  contactName: string;
  email: string;
  phone: string;
  postalCode: string;
  address: string;
  industry: string;
  status: string;
  rank: string;
  salesRep: string;
  createdAt: string;
  updatedAt: string;
  remarks: string;
}

export const dummyCustomers: CustomerItem[] = [
  {
    id: 1,
    customerCode: 'C-001',
    companyName: '株式会社山田製作所',
    department: '製造部',
    contactName: '山田太郎',
    email: 'yamada@yamada-mfg.co.jp',
    phone: '03-1234-5678',
    postalCode: '100-0001',
    address: '東京都千代田区丸の内1-1-1',
    industry: '製造業',
    status: '取引中',
    rank: 'A',
    salesRep: '佐藤花子',
    createdAt: '2024-01-15',
    updatedAt: '2024-12-01',
    remarks: '主要取引先',
  },
  {
    id: 2,
    customerCode: 'C-002',
    companyName: '田中工業株式会社',
    department: '購買部',
    contactName: '田中一郎',
    email: 'tanaka@tanaka-ind.co.jp',
    phone: '06-2345-6789',
    postalCode: '530-0001',
    address: '大阪府大阪市北区梅田2-2-2',
    industry: '製造業',
    status: '取引中',
    rank: 'A',
    salesRep: '鈴木次郎',
    createdAt: '2024-02-20',
    updatedAt: '2024-11-15',
    remarks: '',
  },
  {
    id: 3,
    customerCode: 'C-003',
    companyName: '佐藤商事株式会社',
    department: '営業部',
    contactName: '佐藤美咲',
    email: 'sato@sato-trading.co.jp',
    phone: '052-3456-7890',
    postalCode: '450-0002',
    address: '愛知県名古屋市中村区名駅3-3-3',
    industry: '商社',
    status: '取引中',
    rank: 'B',
    salesRep: '高橋美咲',
    createdAt: '2024-03-10',
    updatedAt: '2024-10-20',
    remarks: '新規開拓先',
  },
  {
    id: 4,
    customerCode: 'C-004',
    companyName: '鈴木電機株式会社',
    department: '技術部',
    contactName: '鈴木健太',
    email: 'suzuki@suzuki-elec.co.jp',
    phone: '045-4567-8901',
    postalCode: '220-0012',
    address: '神奈川県横浜市西区みなとみらい4-4-4',
    industry: '電機',
    status: '休眠',
    rank: 'C',
    salesRep: '伊藤健太',
    createdAt: '2023-06-05',
    updatedAt: '2024-03-10',
    remarks: '連絡待ち',
  },
  {
    id: 5,
    customerCode: 'C-005',
    companyName: '高橋建設株式会社',
    department: '工事部',
    contactName: '高橋誠',
    email: 'takahashi@takahashi-const.co.jp',
    phone: '011-5678-9012',
    postalCode: '060-0001',
    address: '北海道札幌市中央区北1条西5-5-5',
    industry: '建設',
    status: '取引中',
    rank: 'B',
    salesRep: '渡辺真理',
    createdAt: '2024-04-15',
    updatedAt: '2024-11-30',
    remarks: '',
  },
  {
    id: 6,
    customerCode: 'C-006',
    companyName: '伊藤物流株式会社',
    department: '総務部',
    contactName: '伊藤真理',
    email: 'ito@ito-logistics.co.jp',
    phone: '092-6789-0123',
    postalCode: '812-0011',
    address: '福岡県福岡市博多区博多駅前6-6-6',
    industry: '物流',
    status: '見込み',
    rank: 'B',
    salesRep: '小林誠',
    createdAt: '2024-05-20',
    updatedAt: '2024-12-05',
    remarks: '来月商談予定',
  },
  {
    id: 7,
    customerCode: 'C-007',
    companyName: '渡辺食品株式会社',
    department: '製造部',
    contactName: '渡辺洋子',
    email: 'watanabe@watanabe-food.co.jp',
    phone: '082-7890-1234',
    postalCode: '730-0011',
    address: '広島県広島市中区基町7-7-7',
    industry: '食品',
    status: '取引中',
    rank: 'A',
    salesRep: '佐藤花子',
    createdAt: '2023-12-01',
    updatedAt: '2024-11-25',
    remarks: '定期発注あり',
  },
  {
    id: 8,
    customerCode: 'C-008',
    companyName: '小林機械株式会社',
    department: '設計部',
    contactName: '小林浩二',
    email: 'kobayashi@kobayashi-mach.co.jp',
    phone: '022-8901-2345',
    postalCode: '980-0021',
    address: '宮城県仙台市青葉区中央8-8-8',
    industry: '機械',
    status: '取引中',
    rank: 'B',
    salesRep: '鈴木次郎',
    createdAt: '2024-01-25',
    updatedAt: '2024-10-15',
    remarks: '',
  },
  {
    id: 9,
    customerCode: 'C-009',
    companyName: '加藤化学工業株式会社',
    department: '研究開発部',
    contactName: '加藤隆',
    email: 'kato@kato-chem.co.jp',
    phone: '078-9012-3456',
    postalCode: '650-0021',
    address: '兵庫県神戸市中央区三宮町9-9-9',
    industry: '化学',
    status: '見込み',
    rank: 'C',
    salesRep: '高橋美咲',
    createdAt: '2024-06-10',
    updatedAt: '2024-12-10',
    remarks: 'サンプル送付済み',
  },
  {
    id: 10,
    customerCode: 'C-010',
    companyName: '吉田精密株式会社',
    department: '品質管理部',
    contactName: '吉田明',
    email: 'yoshida@yoshida-prec.co.jp',
    phone: '048-0123-4567',
    postalCode: '330-0854',
    address: '埼玉県さいたま市大宮区桜木町10-10-10',
    industry: '精密機器',
    status: '取引中',
    rank: 'A',
    salesRep: '伊藤健太',
    createdAt: '2023-09-15',
    updatedAt: '2024-11-20',
    remarks: '重要顧客',
  },
];
